import { CSSProperties } from "react";

export const typography: Record<string, CSSProperties> = {
  "display-xl": {
    fontFamily: "var(--font-display)",
    fontSize: 64,
    fontWeight: 600,
    lineHeight: 1.05,
    letterSpacing: "-2px",
  },
  "display-lg": {
    fontFamily: "var(--font-display)",
    fontSize: 48,
    fontWeight: 600,
    lineHeight: 1.1,
    letterSpacing: "-1.5px",
  },
  "display-md": {
    fontFamily: "var(--font-display)",
    fontSize: 36,
    fontWeight: 600,
    lineHeight: 1.15,
    letterSpacing: "-1px",
  },
  "display-sm": {
    fontFamily: "var(--font-display)",
    fontSize: 28,
    fontWeight: 600,
    lineHeight: 1.2,
    letterSpacing: "-0.5px",
  },
  "title-lg": {
    fontFamily: "var(--font-body)",
    fontSize: 22,
    fontWeight: 600,
    lineHeight: 1.3,
    letterSpacing: "-0.3px",
  },
  "title-md": {
    fontFamily: "var(--font-body)",
    fontSize: 18,
    fontWeight: 600,
    lineHeight: 1.4,
    letterSpacing: 0,
  },
  "title-sm": {
    fontFamily: "var(--font-body)",
    fontSize: 16,
    fontWeight: 600,
    lineHeight: 1.4,
    letterSpacing: 0,
  },
  "body-md": {
    fontFamily: "var(--font-body)",
    fontSize: 16,
    fontWeight: 400,
    lineHeight: 1.5,
    letterSpacing: 0,
  },
  "body-sm": {
    fontFamily: "var(--font-body)",
    fontSize: 14,
    fontWeight: 400,
    lineHeight: 1.5,
    letterSpacing: 0,
  },
  caption: {
    fontFamily: "var(--font-body)",
    fontSize: 13,
    fontWeight: 500,
    lineHeight: 1.4,
    letterSpacing: 0,
  },
  code: {
    fontFamily: "var(--font-code)",
    fontSize: 14,
    fontWeight: 400,
    lineHeight: 1.5,
    letterSpacing: 0,
  },
  button: {
    fontFamily: "var(--font-body)",
    fontSize: 14,
    fontWeight: 600,
    lineHeight: 1,
    letterSpacing: 0,
  },
  "nav-link": {
    fontFamily: "var(--font-body)",
    fontSize: 14,
    fontWeight: 500,
    lineHeight: 1.4,
    letterSpacing: 0,
  },
};
